name: Build StyleSnap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-pc-windows-msvc
    
    - name: Install dependencies
      working-directory: frontend
      run: npm ci
    
    - name: Build Windows ARM64
      working-directory: frontend
      run: npm run tauri build -- --target aarch64-pc-windows-msvc
    
    - name: Upload Windows ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm64
        path: frontend/src-tauri/target/aarch64-pc-windows-msvc/release/bundle/
  
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin
    
    - name: Install dependencies
      working-directory: frontend
      run: npm ci
    
    - name: Build macOS ARM64
      working-directory: frontend
      run: npm run tauri:build
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64
        path: frontend/src-tauri/target/release/bundle/
